### ISSUE TITLE
[grafana] grafana-init-sc-datasources fails with k8s-sidecar:1.21.0

### ISSUE THREAD

**Issue by danielpof** [grafana/helm-charts#2073]
When attempting to upgrade to helm chart version 6.48 the `grafana-init-sc-datasources` initContainer fails with with following error:

```log
2022-12-19T15:47:39+00:00	AttributeError: 'V1Secret' object has no attribute 'binary_data'
2022-12-19T15:47:39+00:00	       ^^^^^^^^^^^^^^^^^^^^^^
2022-12-19T15:47:39+00:00	    if config_map.binary_data is not None:
2022-12-19T15:47:39+00:00	  File "/app/resources.py", line 206, in _process_config_map
2022-12-19T15:47:39+00:00	                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-12-19T15:47:39+00:00	    files_changed |= _process_config_map(dest_folder, item, resource, unique_filenames, enable_5xx, True)
2022-12-19T15:47:39+00:00	  File "/app/resources.py", line 123, in list_resources
2022-12-19T15:47:39+00:00	    list_resources(label, label_value, target_folder, request_url, request_method, request_payload,
2022-12-19T15:47:39+00:00	  File "/app/sidecar.py", line 113, in main
2022-12-19T15:47:39+00:00	    main()
2022-12-19T15:47:39+00:00	  File "/app/sidecar.py", line 155, in <module>
2022-12-19T15:47:39+00:00	Traceback (most recent call last):
2022-12-19T15:47:38+00:00	{"time": "2022-12-19T15:47:38.332576+00:00", "level": "INFO", "msg": "5xx response content will not be enabled."}
2022-12-19T15:47:38+00:00	{"time": "2022-12-19T15:47:38.332504+00:00", "level": "INFO", "msg": "Unique filenames will not be enforced."}
2022-12-19T15:47:38+00:00	{"time": "2022-12-19T15:47:38.332401+00:00", "level": "INFO", "msg": "Config for cluster api at 'https://10.0.0.1:443' loaded..."}
2022-12-19T15:47:38+00:00	{"time": "2022-12-19T15:47:38.331801+00:00", "level": "INFO", "msg": "Loading incluster config ..."}
2022-12-19T15:47:38+00:00	{"time": "2022-12-19T15:47:38.331629+00:00", "level": "WARNING", "msg": "No folder annotation was provided, defaulting to k8s-sidecar-target-directory"}
2022-12-19T15:47:38+00:00	{"time": "2022-12-19T15:47:38.331378+00:00", "level": "INFO", "msg": "Starting collector"}
2022-12-19T15:47:46+00:00	AttributeError: 'V1Secret' object has no attribute 'binary_data'
2022-12-19T15:47:46+00:00	       ^^^^^^^^^^^^^^^^^^^^^^
2022-12-19T15:47:46+00:00	    if config_map.binary_data is not None:
2022-12-19T15:47:46+00:00	  File "/app/resources.py", line 206, in _process_config_map
2022-12-19T15:47:46+00:00	                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2022-12-19T15:47:46+00:00	    files_changed |= _process_config_map(dest_folder, item, resource, unique_filenames, enable_5xx, True)
2022-12-19T15:47:46+00:00	  File "/app/resources.py", line 123, in list_resources
2022-12-19T15:47:46+00:00	    list_resources(label, label_value, target_folder, request_url, request_method, request_payload,
2022-12-19T15:47:46+00:00	  File "/app/sidecar.py", line 113, in main
2022-12-19T15:47:46+00:00	    main()
2022-12-19T15:47:46+00:00	  File "/app/sidecar.py", line 155, in <module>
2022-12-19T15:47:46+00:00	Traceback (most recent call last):
2022-12-19T15:47:42+00:00	{"time": "2022-12-19T15:47:42.404796+00:00", "level": "INFO", "msg": "5xx response content will not be enabled."}
2022-12-19T15:47:42+00:00	{"time": "2022-12-19T15:47:42.404685+00:00", "level": "INFO", "msg": "Unique filenames will not be enforced."}
2022-12-19T15:47:42+00:00	{"time": "2022-12-19T15:47:42.404562+00:00", "level": "INFO", "msg": "Config for cluster api at 'https://10.0.0.1:443' loaded..."}
2022-12-19T15:47:42+00:00	{"time": "2022-12-19T15:47:42.403914+00:00", "level": "INFO", "msg": "Loading incluster config ..."}
2022-12-19T15:47:42+00:00	{"time": "2022-12-19T15:47:42.403768+00:00", "level": "WARNING", "msg": "No folder annotation was provided, defaulting to k8s-sidecar-target-directory"}
2022-12-19T15:47:42+00:00	{"time": "2022-12-19T15:47:42.403592+00:00", "level": "INFO", "msg": "Starting collector"}
```

forcing tag `1.20.0` for  `k8s-sidecar` allows grafana to start without errors.

Kubernetes Version: 1.23.8
Platform: Azure Kubernetes Services

**Comment by zanhsieh** [comment]
@Arabus 
Could you look into this problem please? Similar to this

[AttributeError: 'V1Secret' object has no attribute 'binary_data'](https://github.com/kiwigrid/k8s-sidecar/issues/110)

If sidecar 1.21.0 doesn't go well, just rollback to 1.20.0.
