### ISSUE TITLE
[too many 500 error responses] on creating grafana alerts using sidecar

### ISSUE THREAD

**Issue by cxsimon** [grafana/helm-charts#2376]
Trying to add grafana alert using sidecar.
values.yaml:
```
sidecar:
  dashboards:
    enabled: true
    searchNamespace: ALL
  alerts:
    enabled: true
    earchNamespace: ALL
```
Setting up an alert using a secret (couldn't find a way to set as a configmap), provisioned this yaml:
```
apiVersion: v1
kind: Secret
metadata:
  namespace: monitirng
  name: test-alert-1
  labels:
    grafana_alert: "1"
type: Opaque
data:
  rules.yaml:
    YXBMQogIGdyb (base64value)
```
grafana-sc-alerts files are empty and no alerts in grafana ui also
```
/etc/grafana/provisioning/alerting $ ls -l
total 0
-rwxr-xr-x    1 root     472              0 Apr 30 14:42 contactpoints.yaml
-rwxr-xr-x    1 root     472              0 Apr 30 14:42 rules.yaml
/etc/grafana/provisioning/alerting $ cat rules.yaml
/etc/grafana/provisioning/alerting $ cat contactpoints.yaml
```
looking at the logs looks like I got permission denied 
```
{"time": "2023-05-01T12:53:28.491544+00:00", "level": "INFO", "msg": "Starting collector"}
{"time": "2023-05-01T12:53:28.491709+00:00", "level": "WARNING", "msg": "No folder annotation was provided, defaulting to k8s-sidecar-target-directory"}
{"time": "2023-05-01T12:53:28.491868+00:00", "level": "INFO", "msg": "Loading incluster config ..."}
{"time": "2023-05-01T12:53:28.492445+00:00", "level": "INFO", "msg": "Config for cluster api at 'https://10.100.0.1:443' loaded..."}
{"time": "2023-05-01T12:53:28.492563+00:00", "level": "INFO", "msg": "Unique filenames will not be enforced."}
{"time": "2023-05-01T12:53:28.492681+00:00", "level": "INFO", "msg": "5xx response content will not be enabled."}
{"time": "2023-05-01T12:54:06.625835+00:00", "level": "ERROR", "msg": "Received unknown exception: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/admin/provisioning/alerting/reload (Caused by ResponseError('too many 500 error responses'))\n"}
Traceback (most recent call last):
  File "/app/.venv/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 878, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  [Previous line repeated 2 more times]
  File "/app/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 868, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/admin/provisioning/alerting/reload (Caused by ResponseError('too many 500 error responses'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/resources.py", line 347, in _watch_resource_loop
    _watch_resource_iterator(*args)
  File "/app/resources.py", line 335, in _watch_resource_iterator
    request(request_url, request_method, enable_5xx, request_payload)
  File "/app/helpers.py", line 132, in request
    res = r.post("%s" % url, auth=auth, json=payload, timeout=REQ_TIMEOUT)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/requests/sessions.py", line 635, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/requests/adapters.py", line 556, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/admin/provisioning/alerting/reload (Caused by ResponseError('too many 500 error responses'))
```

**Comment by cxsimon** [comment]
Configuration with configmap works:
```
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: infra
  name: test-alert-1
  labels:
    grafana_alert: "1"
data:
  rules.yaml: |
    apiVersion: 1
    groups: .........
```
